### PR TITLE
Fix SelectTeamMenu can be stacked infinitely

### PR DESCRIPTION
**Pull request by OcZi**
Reported in BRAIN/OUT Discord:
imagen_2022-06-23_053146717

Popping any SelectTeamMenu of menu stack before opening it will fix the problem.

### CODE REVIEW

**Comment by desertkun** [comment]
@OcZi could you please rebase (or merge master into) this branch? CI is failing.

**Comment by OcZi** [comment]
> @OcZi could you please rebase (or merge master into) this branch? CI is failing.

Done

**Comment by OcZi** [comment]
> @OcZi could you please rebase (or merge master into) this branch? CI is failing.

Done

**Comment by OcZi** [comment]
> @OcZi could you please rebase (or merge master into) this branch? CI is failing.

Done

**Pull request merged**
